# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2004

# Custom your favicon.ico in `site/source`
favicon: /favicon.png

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  # Tags: /tags
  # Categories: /categories
  About: /about

# default page mode: default | archives
mode: archives

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  fancybox: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: true
  qrCode:
    wechat: http://7qn9uj.com1.z0.glb.clouddn.com/cress-rewardQR-wx.jpg
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: cress@duran.im
  stack-overflow:
  twitter: https://twitter.com/supercress
  facebook:
  linkedin:
  google:
  github: https://github.com/cresstoo
  weibo:
  zhihu:
  doubai:
  pocket:
  tumblr:
  instagram: https://instagram.com/kuresu

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics: UA-56488433-2
# Google Verification
google_verification:

# Disqus
disqus_shortname: imduran

#Changyan
changyan:
  appid:
  appkey:

# ===========================================
# Version
# ===========================================
version: 2.6.0
